httpTimeout: 600000
nodeLinker: node-modules
defaultSemverRangePrefix: ''
npmRegistryServer: "https://registry.npmmirror.com"
yarnPath: .yarn/releases/yarn-3.7.0.cjs
supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
  cpu:
    - 'x64'
    - 'arm64'
  libc:
    - 'glibc'
    - 'musl'