// 根据 Figma Variables 生成

import type { OptionalConfig } from 'tailwindcss/types/config';

export const theme: OptionalConfig['theme'] = {
  extend: {
    colors: {
      'base-black': 'var(--base-black)',
      'base-white': 'var(--base-white)',
      'base-white-80': 'var(--base-white-80)',
      'base-white-60': 'var(--base-white-60)',
      'base-white-50': 'var(--base-white-50)',
      'grey-50': 'var(--grey-50)',
      'grey-100': 'var(--grey-100)',
      'grey-200': 'var(--grey-200)',
      'grey-300': 'var(--grey-300)',
      'grey-400': 'var(--grey-400)',
      'grey-500': 'var(--grey-500)',
      'grey-600': 'var(--grey-600)',
      'grey-700': 'var(--grey-700)',
      'grey-800': 'var(--grey-800)',
      'grey-900': 'var(--grey-900)',
      'grey-950': 'var(--grey-950)',
      'grey-1000': 'var(--grey-1000)',
      'grey-1050': 'var(--grey-1050)',
      'purple-50': 'var(--purple-50)',
      'purple-100': 'var(--purple-100)',
      'purple-200': 'var(--purple-200)',
      'purple-300': 'var(--purple-300)',
      'purple-400': 'var(--purple-400)',
      'purple-500': 'var(--purple-500)',
      'purple-600': 'var(--purple-600)',
      'purple-700': 'var(--purple-700)',
      'purple-800': 'var(--purple-800)',
      'purple-900': 'var(--purple-900)',
      'green-50': 'var(--green-50)',
      'green-100': 'var(--green-100)',
      'green-200': 'var(--green-200)',
      'green-300': 'var(--green-300)',
      'green-400': 'var(--green-400)',
      'green-500': 'var(--green-500)',
      'green-600': 'var(--green-600)',
      'green-700': 'var(--green-700)',
      'green-800': 'var(--green-800)',
      'green-900': 'var(--green-900)',
      'olivine-50': 'var(--olivine-50)',
      'olivine-100': 'var(--olivine-100)',
      'olivine-200': 'var(--olivine-200)',
      'olivine-300': 'var(--olivine-300)',
      'olivine-400': 'var(--olivine-400)',
      'olivine-500': 'var(--olivine-500)',
      'olivine-600': 'var(--olivine-600)',
      'olivine-700': 'var(--olivine-700)',
      'olivine-800': 'var(--olivine-800)',
      'olivine-900': 'var(--olivine-900)',
      'yellow-50': 'var(--yellow-50)',
      'yellow-100': 'var(--yellow-100)',
      'yellow-200': 'var(--yellow-200)',
      'yellow-300': 'var(--yellow-300)',
      'yellow-400': 'var(--yellow-400)',
      'yellow-500': 'var(--yellow-500)',
      'yellow-600': 'var(--yellow-600)',
      'yellow-700': 'var(--yellow-700)',
      'yellow-800': 'var(--yellow-800)',
      'yellow-900': 'var(--yellow-900)',
      'orange-50': 'var(--orange-50)',
      'orange-100': 'var(--orange-100)',
      'orange-200': 'var(--orange-200)',
      'orange-300': 'var(--orange-300)',
      'orange-400': 'var(--orange-400)',
      'orange-500': 'var(--orange-500)',
      'orange-600': 'var(--orange-600)',
      'orange-700': 'var(--orange-700)',
      'orange-800': 'var(--orange-800)',
      'orange-900': 'var(--orange-900)',
      'red-50': 'var(--red-50)',
      'red-100': 'var(--red-100)',
      'red-200': 'var(--red-200)',
      'red-300': 'var(--red-300)',
      'red-400': 'var(--red-400)',
      'red-500': 'var(--red-500)',
      'red-600': 'var(--red-600)',
      'red-700': 'var(--red-700)',
      'red-800': 'var(--red-800)',
      'red-900': 'var(--red-900)',
      'deep-red-50': 'var(--deep-red-50)',
      'deep-red-100': 'var(--deep-red-100)',
      'deep-red-200': 'var(--deep-red-200)',
      'deep-red-300': 'var(--deep-red-300)',
      'deep-red-400': 'var(--deep-red-400)',
      'deep-red-500': 'var(--deep-red-500)',
      'deep-red-600': 'var(--deep-red-600)',
      'deep-red-700': 'var(--deep-red-700)',
      'deep-red-800': 'var(--deep-red-800)',
      'deep-red-900': 'var(--deep-red-900)',
      'blue-50': 'var(--blue-50)',
      'blue-100': 'var(--blue-100)',
      'blue-200': 'var(--blue-200)',
      'blue-300': 'var(--blue-300)',
      'blue-400': 'var(--blue-400)',
      'blue-500': 'var(--blue-500)',
      'blue-600': 'var(--blue-600)',
      'blue-700': 'var(--blue-700)',
      'blue-800': 'var(--blue-800)',
      'blue-900': 'var(--blue-900)',
      'azure-50': 'var(--azure-50)',
      'azure-100': 'var(--azure-100)',
      'azure-200': 'var(--azure-200)',
      'azure-300': 'var(--azure-300)',
      'azure-400': 'var(--azure-400)',
      'azure-500': 'var(--azure-500)',
      'azure-600': 'var(--azure-600)',
      'azure-700': 'var(--azure-700)',
      'azure-800': 'var(--azure-800)',
      'azure-900': 'var(--azure-900)',
      'text-1': 'var(--text-1)',
      'text-2': 'var(--text-2)',
      'text-3': 'var(--text-3)',
      'text-4': 'var(--text-4)',
      'text-white': 'var(--text-white)',
      'text-white-80': 'var(--text-white-80)',
      'primary-normal': 'var(--primary-normal)',
      'primary-hover': 'var(--primary-hover)',
      'primary-click': 'var(--primary-click)',
      'primary-disable': 'var(--primary-disable)',
      'primary-bg': 'var(--primary-bg)',
      'icon-status-outlined-hover': 'var(--icon-status-outlined-hover)',
      'success-normal': 'var(--success-normal)',
      'success-hover': 'var(--success-hover)',
      'success-click': 'var(--success-click)',
      'success-disable': 'var(--success-disable)',
      'icon-status-outlined-click': 'var(--icon-status-outlined-click)',
      'success-bg': 'var(--success-bg)',
      'icon-status-outlined-disable': 'var(--icon-status-outlined-disable)',
      'icon-status-outlined-active': 'var(--icon-status-outlined-active)',
      'icon-status-filled-hover': 'var(--icon-status-filled-hover)',
      'icon-status-filled-click': 'var(--icon-status-filled-click)',
      'warning-normal': 'var(--warning-normal)',
      'warning-hover': 'var(--warning-hover)',
      'warning-click': 'var(--warning-click)',
      'warning-disable': 'var(--warning-disable)',
      'warning-bg': 'var(--warning-bg)',
      'danger-normal': 'var(--danger-normal)',
      'danger-hover': 'var(--danger-hover)',
      'danger-click': 'var(--danger-click)',
      'danger-disable': 'var(--danger-disable)',
      'danger-bg': 'var(--danger-bg)',
      'critical-normal': 'var(--critical-normal)',
      'critical-hover': 'var(--critical-hover)',
      'critical-click': 'var(--critical-click)',
      'critical-disable': 'var(--critical-disable)',
      'critical-bg': 'var(--critical-bg)',
      'updating-normal': 'var(--updating-normal)',
      'updating-hover': 'var(--updating-hover)',
      'updating-click': 'var(--updating-click)',
      'updating-disable': 'var(--updating-disable)',
      'updating-bg': 'var(--updating-bg)',
      'offline-normal': 'var(--offline-normal)',
      'offline-hover': 'var(--offline-hover)',
      'offline-click': 'var(--offline-click)',
      'offline-disable': 'var(--offline-disable)',
      'offline-bg': 'var(--offline-bg)',
      'background-default': 'var(--background-default)',
      'fill-white': 'var(--fill-white)',
      'fill-1': 'var(--fill-1)',
      'fill-2': 'var(--fill-2)',
      'fill-3': 'var(--fill-3)',
      'icon-outlined-operable': 'var(--icon-outlined-operable)',
      'fill-on-grey-1': 'var(--fill-on-grey-1)',
      'fill-on-grey-2': 'var(--fill-on-grey-2)',
      'fill-on-grey-3': 'var(--fill-on-grey-3)',
      'icon-outlined-displayed': 'var(--icon-outlined-displayed)',
      'icon-filled-normal': 'var(--icon-filled-normal)',
      'icon-white': 'var(--icon-white)',
      'icon-status-filled-disable': 'var(--icon-status-filled-disable)',
      'icon-status-filled-active': 'var(--icon-status-filled-active)',
      'icon-status-on-grey-normal': 'var(--icon-status-on-grey-normal)',
      'icon-status-on-grey-hover': 'var(--icon-status-on-grey-hover)',
      'icon-status-on-grey-click': 'var(--icon-status-on-grey-click)',
      'icon-status-on-grey-active': 'var(--icon-status-on-grey-active)',
      'icon-status-on-grey-warning-normal': 'var(--icon-status-on-grey-warning-normal)',
      'icon-status-on-grey-warning-hover': 'var(--icon-status-on-grey-warning-hover)',
      'icon-status-on-grey-warning-click': 'var(--icon-status-on-grey-warning-click)',
      'icon-status-on-grey-warning-active': 'var(--icon-status-on-grey-warning-active)',
      'icon-bg-default-hover': 'var(--icon-bg-default-hover)',
      'icon-bg-default-click': 'var(--icon-bg-default-click)',
      'divider-solid': 'var(--divider-solid)',
      'divider-dash': 'var(--divider-dash)',
      'divider-solid-on-grey': 'var(--divider-solid-on-grey)',
      'divider-dash-on-grey': 'var(--divider-dash-on-grey)',
      'stroke-border-2': 'var(--stroke-border-2)',
      'stroke-border-1': 'var(--stroke-border-1)',
      'text-link-primary-normal': 'var(--text-link-primary-normal)',
      'text-link-primary-hover': 'var(--text-link-primary-hover)',
      'text-link-primary-click': 'var(--text-link-primary-click)',
      'text-link-primary-disable': 'var(--text-link-primary-disable)',
      'text-link-first-normal': 'var(--text-link-first-normal)',
      'text-link-first-hover': 'var(--text-link-first-hover)',
      'text-link-first-click': 'var(--text-link-first-click)',
      'text-link-first-disable': 'var(--text-link-first-disable)',
      'text-link-second-normal': 'var(--text-link-second-normal)',
      'text-link-second-hover': 'var(--text-link-second-hover)',
      'text-link-second-click': 'var(--text-link-second-click)',
      'text-link-second-disable': 'var(--text-link-second-disable)',
      'text-link-success-normal': 'var(--text-link-success-normal)',
      'text-link-success-hover': 'var(--text-link-success-hover)',
      'text-link-success-click': 'var(--text-link-success-click)',
      'text-link-success-disable': 'var(--text-link-success-disable)',
      'text-link-warning-normal': 'var(--text-link-warning-normal)',
      'text-link-warning-hover': 'var(--text-link-warning-hover)',
      'text-link-warning-click': 'var(--text-link-warning-click)',
      'text-link-warning-disable': 'var(--text-link-warning-disable)',
      'text-link-danger-normal': 'var(--text-link-danger-normal)',
      'text-link-danger-hover': 'var(--text-link-danger-hover)',
      'text-link-danger-click': 'var(--text-link-danger-click)',
      'text-link-danger-disable': 'var(--text-link-danger-disable)',
      'text-link-critical-normal': 'var(--text-link-critical-normal)',
      'text-link-critical-hover': 'var(--text-link-critical-hover)',
      'text-link-critical-click': 'var(--text-link-critical-click)',
      'text-link-critical-disable': 'var(--text-link-critical-disable)',
      'text-link-updating-normal': 'var(--text-link-updating-normal)',
      'text-link-updating-hover': 'var(--text-link-updating-hover)',
      'text-link-updating-click': 'var(--text-link-updating-click)',
      'text-link-updating-disable': 'var(--text-link-updating-disable)',
      'chart-read': 'var(--chart-read)',
      'chart-write': 'var(--chart-write)',
      'chart-recovery': 'var(--chart-recovery)',
      'chart-no-meaning-1': 'var(--chart-no-meaning-1)',
      'chart-no-meaning-2': 'var(--chart-no-meaning-2)',
      'chart-no-meaning-3': 'var(--chart-no-meaning-3)',
      'chart-no-meaning-4': 'var(--chart-no-meaning-4)',
      'chart-no-meaning-5': 'var(--chart-no-meaning-5)',
      'chart-no-meaning-6': 'var(--chart-no-meaning-6)',
      'chart-no-meaning-7': 'var(--chart-no-meaning-7)',
      'chart-no-meaning-8': 'var(--chart-no-meaning-8)',
      'chart-no-meaning-9': 'var(--chart-no-meaning-9)',
      'chart-no-meaning-10': 'var(--chart-no-meaning-10)',
      'chart-no-meaning-11': 'var(--chart-no-meaning-11)',
      'chart-reading': 'var(--chart-reading)',
      'chart-delete': 'var(--chart-delete)',
      'chart-success': 'var(--chart-success)',
      'chart-cache-partitioning': 'var(--chart-cache-partitioning)',
      'chart-log-partition': 'var(--chart-log-partition)',
      'chart-Unused': 'var(--chart-Unused)',
      'chart-bar-1': 'var(--chart-bar-1)',
      'chart-more-read-1': 'var(--chart-more-read-1)',
      'chart-more-read-2': 'var(--chart-more-read-2)',
      'chart-more-read-3': 'var(--chart-more-read-3)',
      'chart-more-write-1': 'var(--chart-more-write-1)',
      'chart-more-write-2': 'var(--chart-more-write-2)',
      'chart-more-write-3': 'var(--chart-more-write-3)',
      'chart-bar-2': 'var(--chart-bar-2)',
      'chart-bar-3': 'var(--chart-bar-3)',
      'chart-bar-4': 'var(--chart-bar-4)',
      'chart-bar-5': 'var(--chart-bar-5)',
      'conditional-top-SDDC-item-hover': 'var(--conditional-top-SDDC-item-hover)',
      'conditional-top-SDDC-item-click': 'var(--conditional-top-SDDC-item-click)',
      'conditional-top-SDDC-item-selected': 'var(--conditional-top-SDDC-item-selected)',
      'conditional-top-SDDC-popupMenu-bg': 'var(--conditional-top-SDDC-popupMenu-bg)',
      'conditional-top-SDDC-popupMenu-item-hover':
        'var(--conditional-top-SDDC-popupMenu-item-hover)',
      'conditional-top-SDDC-popupMenu-item-click':
        'var(--conditional-top-SDDC-popupMenu-item-click)',
      'conditional-top-SDDC-popupMenu-divider': 'var(--conditional-top-SDDC-popupMenu-divider)',
      'conditional-top-background': 'var(--conditional-top-background)',
      'conditional-left-item-hover': 'var(--conditional-left-item-hover)',
      'conditional-left-item-click': 'var(--conditional-left-item-click)',
      'conditional-left-SDDC-item-hover': 'var(--conditional-left-SDDC-item-hover)',
      'conditional-left-SDDC-item-click': 'var(--conditional-left-SDDC-item-click)',
      'icon-bg-danger-hover': 'var(--icon-bg-danger-hover)',
      'icon-bg-danger-click': 'var(--icon-bg-danger-click)',
      'chart-bar-6': 'var(--chart-bar-6)',
      'chart-bar-7': 'var(--chart-bar-7)',
      'chart-bar-8': 'var(--chart-bar-8)',
      'chart-bar-9': 'var(--chart-bar-9)',
      'chart-bar-10': 'var(--chart-bar-10)',
      'chart-bar-11': 'var(--chart-bar-11)',
      'button-bg-secondary-normal': 'var(--button-bg-secondary-normal)',
      'button-bg-secondary-hover': 'var(--button-bg-secondary-hover)',
      'button-bg-secondary-active': 'var(--button-bg-secondary-active)',
      'button-bg-secondary-disable': 'var(--button-bg-secondary-disable)',
      'button-bg-text-normal': 'var(--button-bg-text-normal)',
      'button-bg-text-hover': 'var(--button-bg-text-hover)',
      'button-bg-text-active': 'var(--button-bg-text-active)',
      'button-bg-text-disable': 'var(--button-bg-text-disable)',
      'button-text-secondary_primary-disable': 'var(--button-text-secondary_primary-disable)',
      'button-text-secondary_danger-disable': 'var(--button-text-secondary_danger-disable)',
      'button-text-outline_primary-disable': 'var(--button-text-outline_primary-disable)',
      'button-text-outline_danger-disable': 'var(--button-text-outline_danger-disable)',
      'button-text-text_primary-disable': 'var(--button-text-text_primary-disable)',
      'button-text-text_danger-disable': 'var(--button-text-text_danger-disable)',
      'button-border-outline_primary-disable': 'var(--button-border-outline_primary-disable)',
      'button-border-outline_danger-disable': 'var(--button-border-outline_danger-disable)',
      'progress-bg': 'var(--progress-bg)',
      'progress-normal': 'var(--progress-normal)',
      'tag-grey': 'var(--tag-grey)',
      'tag-primary': 'var(--tag-primary)',
      'tag-active': 'var(--tag-active)',
      'tag-warning': 'var(--tag-warning)',
      'tag-danger': 'var(--tag-danger)',
      'tag-critical': 'var(--tag-critical)',
      'tag-updating': 'var(--tag-updating)',
      'switch-chart-purple-normal': 'var(--switch-chart-purple-normal)',
      'switch-chart-purple-hover': 'var(--switch-chart-purple-hover)',
      'switch-chart-purple-click': 'var(--switch-chart-purple-click)',
      'switch-chart-blue-normal': 'var(--switch-chart-blue-normal)',
      'switch-chart-blue-hover': 'var(--switch-chart-blue-hover)',
      'switch-chart-blue-click': 'var(--switch-chart-blue-click)',
      'switch-chart-yellow-normal': 'var(--switch-chart-yellow-normal)',
      'switch-chart-yellow-hover': 'var(--switch-chart-yellow-hover)',
      'switch-chart-yellow-click': 'var(--switch-chart-yellow-click)',
      'switch-chart-grey-normal': 'var(--switch-chart-grey-normal)',
      'switch-chart-grey-hover': 'var(--switch-chart-grey-hover)',
      'switch-chart-grey-click': 'var(--switch-chart-grey-click)',
      'form-bg-normal': 'var(--form-bg-normal)',
      'form-bg-disable': 'var(--form-bg-disable)',
      'form-border-danger-normal': 'var(--form-border-danger-normal)',
      'form-border-danger-hover': 'var(--form-border-danger-hover)',
      'form-border-danger-focus': 'var(--form-border-danger-focus)',
      'form-border-danger-active': 'var(--form-border-danger-active)',
      'form-border-default-normal': 'var(--form-border-default-normal)',
      'form-border-default-hover': 'var(--form-border-default-hover)',
      'form-border-default-focus': 'var(--form-border-default-focus)',
      'form-border-default-active': 'var(--form-border-default-active)',
      'form-border-default-disable': 'var(--form-border-default-disable)',
      'tree-bg-normal': 'var(--tree-bg-normal)',
      'tree-bg-hover': 'var(--tree-bg-hover)',
      'tree-bg-active': 'var(--tree-bg-active)',
      'tree-bg-selected': 'var(--tree-bg-selected)',
      'tree-bg-disable': 'var(--tree-bg-disable)',
      'skeleton-bg-default': 'var(--skeleton-bg-default)',
      'skeleton-bg-deepen': 'var(--skeleton-bg-deepen)',
      'checkbox-bg-checked-normal': 'var(--checkbox-bg-checked-normal)',
      'checkbox-bg-checked-hover': 'var(--checkbox-bg-checked-hover)',
      'checkbox-bg-checked-focus': 'var(--checkbox-bg-checked-focus)',
      'checkbox-bg-checked-active': 'var(--checkbox-bg-checked-active)',
      'checkbox-bg-checked-disable': 'var(--checkbox-bg-checked-disable)',
      'checkbox-bg-default-normal': 'var(--checkbox-bg-default-normal)',
      'checkbox-bg-default-hover': 'var(--checkbox-bg-default-hover)',
      'checkbox-bg-default-focus': 'var(--checkbox-bg-default-focus)',
      'checkbox-bg-default-active': 'var(--checkbox-bg-default-active)',
      'checkbox-bg-default-disable': 'var(--checkbox-bg-default-disable)',
      'checkbox-border-checked-normal': 'var(--checkbox-border-checked-normal)',
      'checkbox-border-checked-hover': 'var(--checkbox-border-checked-hover)',
      'checkbox-border-checked-focus': 'var(--checkbox-border-checked-focus)',
      'checkbox-border-checked-active': 'var(--checkbox-border-checked-active)',
      'checkbox-border-checked-disable': 'var(--checkbox-border-checked-disable)',
      'checkbox-border-default-normal': 'var(--checkbox-border-default-normal)',
      'checkbox-border-default-hover': 'var(--checkbox-border-default-hover)',
      'checkbox-border-default-focus': 'var(--checkbox-border-default-focus)',
      'checkbox-border-default-active': 'var(--checkbox-border-default-active)',
      'checkbox-border-default-disable': 'var(--checkbox-border-default-disable)',
      'radio-bg-checked-normal': 'var(--radio-bg-checked-normal)',
      'radio-bg-checked-hover': 'var(--radio-bg-checked-hover)',
      'radio-bg-checked-focus': 'var(--radio-bg-checked-focus)',
      'radio-bg-checked-active': 'var(--radio-bg-checked-active)',
      'radio-bg-checked-disable': 'var(--radio-bg-checked-disable)',
      'radio-bg-default-normal': 'var(--radio-bg-default-normal)',
      'radio-bg-default-hover': 'var(--radio-bg-default-hover)',
      'radio-bg-default-focus': 'var(--radio-bg-default-focus)',
      'radio-bg-default-active': 'var(--radio-bg-default-active)',
      'radio-bg-default-disable': 'var(--radio-bg-default-disable)',
      'radio-border-checked-normal': 'var(--radio-border-checked-normal)',
      'radio-border-checked-hover': 'var(--radio-border-checked-hover)',
      'radio-border-checked-focus': 'var(--radio-border-checked-focus)',
      'radio-border-checked-active': 'var(--radio-border-checked-active)',
      'radio-border-checked-disable': 'var(--radio-border-checked-disable)',
      'radio-border-default-normal': 'var(--radio-border-default-normal)',
      'radio-border-default-hover': 'var(--radio-border-default-hover)',
      'radio-border-default-focus': 'var(--radio-border-default-focus)',
      'radio-border-default-active': 'var(--radio-border-default-active)',
      'radio-border-default-disable': 'var(--radio-border-default-disable)',
      'message-bg-info': 'var(--message-bg-info)',
      'message-bg-success': 'var(--message-bg-success)',
      'message-bg-waring': 'var(--message-bg-waring)',
      'message-bg-danger': 'var(--message-bg-danger)',
      'message-border-info': 'var(--message-border-info)',
      'message-border-success': 'var(--message-border-success)',
      'message-border-waring': 'var(--message-border-waring)',
      'message-border-danger': 'var(--message-border-danger)',
      'alert-bg-info': 'var(--alert-bg-info)',
      'alert-bg-warning': 'var(--alert-bg-warning)',
      'alert-bg-danger': 'var(--alert-bg-danger)',
      'alert-border-info': 'var(--alert-border-info)',
      'alert-border-warning': 'var(--alert-border-warning)',
      'alert-border-danger': 'var(--alert-border-danger)',
      'notification-bg-info': 'var(--notification-bg-info)',
      'notification-bg-success': 'var(--notification-bg-success)',
      'notification-bg-warning': 'var(--notification-bg-warning)',
      'notification-bg-danger': 'var(--notification-bg-danger)',
      'notification-bg-critical': 'var(--notification-bg-critical)',
      'notification-border-info': 'var(--notification-border-info)',
      'notification-border-success': 'var(--notification-border-success)',
      'notification-border-warning': 'var(--notification-border-warning)',
      'notification-border-danger': 'var(--notification-border-danger)',
      'notification-border-critical': 'var(--notification-border-critical)',
    },
    spacing: {
      '0': '0px',
      '1': '8px',
      '2': '16px',
      '3': '24px',
      '4': '32px',
      '5': '40px',
      '6': '48px',
      '7': '56px',
      '8': '64px',
      '9': '72px',
      '10': '80px',
      '0-5': '4px',
      'spacing-none': '0px',
      'spacing-sm': '4px',
      'spacing-md': '8px',
      'spacing-lg': '16px',
      'spacing-xl': '24px',
    },
    borderRadius: {
      xs: '1px',
      sm: '2px',
      md: '4px',
      full: '9999px',
      'radius-special': '1px',
      'radius-sm': '2px',
      'radius-md': '4px',
      'radius-circle': '9999px',
    },
    fontSize: {
      caption: ['12px', '20px'],
      body: ['14px', '22px'],
      subhead: ['16px', '24px'],
      title: ['20px', '28px'],
      number: ['24px', '32px'],
      bignumber: ['32px', '40px'],
      extralarge: ['40px', '48px'],
    },
    boxShadow: {
      'elevation-3-bottom':
        '0px 6px 20px 0px rgba(0, 0, 0, 0.06), 0px 4px 15px 5px rgba(0, 0, 0, 0.03), 0px 4px 10px 2px rgba(0, 0, 0, 0.05);',
      'elevation-3-right':
        '6px 0px 20px 0px rgba(0, 0, 0, 0.06), 4px 0px 15px 5px rgba(0, 0, 0, 0.03), 4px 0px 10px 2px rgba(0, 0, 0, 0.05);',
      'interactive-primary-focus': 'var(--interactive-primary-focus)',
      'elevation-2-bottom':
        '0px 4px 15px 0px rgba(0, 0, 0, 0.06), 0px 2px 8px 0px rgba(0, 0, 0, 0.03), 0px 2px 6px 0px rgba(0, 0, 0, 0.05);',
      'elevation-2-top':
        '0px -4px 15px 0px rgba(0, 0, 0, 0.06), 0px -2px 8px 0px rgba(0, 0, 0, 0.03), 0px -2px 6px 0px rgba(0, 0, 0, 0.05);',
      'interactive-primary-active': 'var(--interactive-primary-active)',
      'elevation-2-right':
        '4px 0px 15px 0px rgba(0, 0, 0, 0.06), 2px 0px 8px 0px rgba(0, 0, 0, 0.03), 2px 0px 6px 0px rgba(0, 0, 0, 0.05);',
      'interactive-danger-focus': '0px 0px 0px 2px rgba(196, 53, 58, 0.15);',
      'elevation-2-left':
        '-4px 0px 15px 0px rgba(0, 0, 0, 0.06), -2px 0px 8px 0px rgba(0, 0, 0, 0.03), -2px 0px 6px 0px rgba(0, 0, 0, 0.05);',
      'interactive-danger-active': '0px 0px 0px 2px rgba(196, 53, 58, 0.30);',
      'elevation-1-bottom':
        '0px 1px 8px 0px rgba(0, 0, 0, 0.06), 0px 1px 4px 0px rgba(0, 0, 0, 0.03), 0px 1px 3px 0px rgba(0, 0, 0, 0.05);',
      'interactive-success-focus': '0px 0px 0px 2px rgba(26, 163, 90, 0.16);',
      'interactive-success-active': '0px 0px 0px 2px rgba(14, 135, 74, 0.24);',
      'elevation-1-top':
        '0px -1px 8px 0px rgba(0, 0, 0, 0.06), 0px -1px 4px 0px rgba(0, 0, 0, 0.03), 0px -1px 3px 0px rgba(0, 0, 0, 0.05);',
      'elevation-1-right':
        '1px 0px 8px 0px rgba(0, 0, 0, 0.06), 1px 0px 4px 0px rgba(0, 0, 0, 0.03), 1px 0px 3px 0px rgba(0, 0, 0, 0.05);',
      'elevation-1-left':
        '-1px 0px 8px 0px rgba(0, 0, 0, 0.06), -1px 0px 4px 0px rgba(0, 0, 0, 0.03), -1px 0px 3px 0px rgba(0, 0, 0, 0.05);',
    },
    height: {
      'skeleton-height-xs': '12px',
      'skeleton-height-sm': '20px',
      'skeleton-height-md': '34px',
      'skeleton-height-lg': '64px',
      'skeleton-height-xl': '100px',
      'skeleton-height-xxl': '150px',
    },
    width: {
      'skeleton-width-xs': '20%',
      'skeleton-width-sm': '40%',
      'skeleton-width-md': '60%',
      'skeleton-width-lg': '80%',
      'skeleton-width-xl': '100%',
    },
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        'Helvetica Neue',
        'Helvetica',
        'Arial',
        'PingFang SC',
        'San Francisco',
        'Noto Sans',
        'Roboto',
        'Microsoft Yahei',
        '微软雅黑',
        'Segoe UI',
        'WenQuanYi Micro Hei',
        'sans-serif',
      ],
    },
  },
};
