name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Publish packages to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Enable Corepack (Yarn Berry)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build all
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn build

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish changed packages to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: node scripts/publish-changed.js
